Roulette guide
api3dao/vitepress-docs pull request #462
Opened 2023-05-08 14:56 UTC by vanshwassan

- Added the roulette guide under the QRNG Guides section.
- Covers the entire roulette smart contract + steps on how to deploy and interact with it using Remix IDE.

2023-05-14 14:40 UTC, Ashar2shahid requested changes
it would be helpful if the coding section can be divided into sections to navigate on the right hand side bar

2023-05-19 03:44 UTC, vanshwassan commented on docs/guides/qrng/roulette-guide/index.md
> +```solidity
Done 👍🏻

2023-05-19 03:45 UTC, vanshwassan commented
> it would be helpful if the coding section can be divided into sections to navigate on the right hand side bar

Yeah, I've added some sub-headings. LMK if it looks good to you.

2023-06-02 15:21 UTC, Ashar2shahid approved these changes

2023-06-02 15:21 UTC, Ashar2shahid commented
@wkande when you get the time can you review this ?

2023-06-02 17:25 UTC, wkande commented
@vanshwassan @Ashar2shahid 

1.  I would add a period after the sentence: "The complete contract code can be found here"
2.  And here as well: "Fill in the amount in wei under VALUE on the tab above and click on topUpSponsorWallet()"
3.  Again: "use betEvenOdd() to bet on either the set of all even or odd numbers on the board"

Other than that this looks good. Of course I did not actually create the app but I feel it will work.

2023-06-07 10:41 UTC, wkande commented
@vanshwassan 

For links that take the reader to an external site add the component <ExternalLinkImage/> to the label.

`[here](https://github.com/Ashar2shahid/qrng-roulette/blob/main/contracts/contracts/Roulette.sol)`

`[here<ExternalLinkImage/>](https://github.com/Ashar2shahid/qrng-roulette/blob/main/contracts/contracts/Roulette.sol)`

Not that there is no space between the label and the component.

2023-06-12 23:36 UTC, Ashar2shahid approved these changes

2023-06-12 23:36 UTC, merged