Qrng faq
api3dao/vitepress-docs pull request #635
Opened 2023-09-29 04:17 UTC by vanshwassan

- Added FAQ as mentioned in [this issue](https://github.com/api3dao/vitepress-docs/issues/627#issue-1899887915). Tried to revamp the getting started section to include both FAQ and the [qrng-example](https://github.com/api3dao/qrng-example) repo within the same page.
- Also added a `CONTRIBUTING.md` markdown for contributors to refer to before making a contribution.

2023-09-29 05:06 UTC, dcroote requested changes

2023-09-29 05:06 UTC, dcroote commented on docs/guides/qrng/index.md
> +```
Nice

2023-09-29 05:06 UTC, dcroote commented on docs/guides/qrng/index.md
> +[here](/reference/airnode/latest/concepts/sponsor.html#sponsorwallet).
```suggestion
[here](/reference/airnode/latest/concepts/sponsor.md#sponsorwallet).
```

2023-09-29 05:06 UTC, dcroote commented on docs/guides/qrng/index.md
> +[derive-sponsor-wallet-address](/reference/airnode/latest/packages/admin-cli.html#derive-sponsor-wallet-address)
```suggestion
[derive-sponsor-wallet-address](/reference/airnode/latest/packages/admin-cli.md#derive-sponsor-wallet-address)
```

2023-09-29 05:09 UTC, dcroote reviewed
Nice FAQ additions.  For `CONTRIBUTING.md`, the content overlaps some with https://docs.api3.org/dev/ - perhaps link to the relevant pages from the appropriate `CONTRIBUTING.md` sections?

2023-10-04 00:14 UTC, vanshwassan commented
> Nice FAQ additions. For `CONTRIBUTING.md`, the content overlaps some with https://docs.api3.org/dev/ - perhaps link to the relevant pages from the appropriate `CONTRIBUTING.md` sections?

Ah I didn't know about this section, added references to this from `CONTRIBUTING.md`.

2023-10-04 04:16 UTC, dcroote approved these changes
A few links need the trailing `/` removed, otherwise nice 👍

2023-10-04 04:16 UTC, dcroote commented on docs/guides/qrng/index.md
> +the [Using QRNG - Remix Example](/guides/qrng/qrng-remix/index.md/) guide.
```suggestion
the [Using QRNG - Remix Example](/guides/qrng/qrng-remix/index.md) guide.
```

2023-10-04 04:16 UTC, dcroote commented on docs/guides/qrng/index.md
> +[Airnode](/reference/airnode/latest/understand/index.md/), the
```suggestion
[Airnode](/reference/airnode/latest/understand/index.md), the
```

2023-10-04 04:16 UTC, dcroote commented on docs/guides/qrng/index.md
> +[here](/reference/qrng/index.md/).
```suggestion
[here](/reference/qrng/index.md).
```

2023-10-10 06:10 UTC, dcroote commented
Any reason not to merge?

2023-10-10 19:53 UTC, Ashar2shahid approved these changes

2023-10-10 19:53 UTC, Ashar2shahid commented
Looks good, can get it merged

2023-10-10 19:54 UTC, merged