Qrng review march15
api3dao/vitepress-docs pull request #721
Opened 2024-04-05 10:48 UTC by KenCarvAPI

Refresh to explore section

2024-04-12 01:41 UTC, vanshwassan requested changes

2024-04-12 01:41 UTC, vanshwassan commented on docs/explore/qrng/index.md
> +There are are currently limited options to access entropy on-chain. API3 Quantum
```suggestion
There are currently limited options to access entropy on-chain. API3 Quantum
```

2024-04-13 05:28 UTC, dcroote commented on docs/explore/qrng/QRNG-providers.md
> +nature.QuintessenceLabs uses quantum tunneling to deliver truly random numbers
Missing space after period

2024-04-13 05:28 UTC, dcroote commented on docs/explore/qrng/index.md
> +<!-- review -->
Delete these comments?

2024-04-13 05:28 UTC, dcroote commented on docs/explore/qrng/index.md
> -See these guides and learn how to use QRNG:
Why not link to the QRNG [getting started guide page](https://docs.api3.org/guides/qrng/)? It seems like we'd want to have an actionable next step after viewing this Explore page.

2024-04-13 05:28 UTC, dcroote commented on docs/reference/qrng/chains.md
> +## ANU Mainnet
Shouldn't this (and the other similar headings) be plural "Mainnets"?

2024-04-20 09:44 UTC, KenCarvAPI commented
@vanshwassan @dcroote thanks for reviewing. Implemented the amends/thoughts. 

@Ashar2shahid this is ready for you to review and merge if happy.

2024-04-20 20:03 UTC, dcroote commented on docs/explore/qrng/index.md
> +Follow [this guide](https://docs.api3.org/guides/qrng/) to get started with QRNG
Nit: change to internal link i.e. no https...

2024-04-20 20:03 UTC, dcroote commented on docs/reference/qrng/chains.md
> +## ANU Mainnets Chain ID
I think this should just be "ANU Mainnets" - the tables have more than just chain IDs (same applies to the other headings).

2024-10-03 16:42 UTC, wkande commented
@dcroote Should we close this PR? QRNG being a thing of the past and all.

2024-10-03 19:36 UTC, dcroote commented
I'm good with closing

2024-10-04 17:24 UTC, Ashar2shahid commented
yes closing

2024-10-04 17:24 UTC, closed without merging