Update dAPI reference and guides section
api3dao/vitepress-docs pull request #723
Opened 2024-04-16 12:30 UTC by vanshwassan

Updated the `/guides` and `/reference` section for dAPIs for the upcoming market updates.
- Removed references regarding Self-funded and Managed dAPIs
- Updated the guides and reference sections for the new market updates and OEV
- Removed the Gelato guide for funding dAPI sponsor wallets

2024-04-24 00:26 UTC, Ashar2shahid approved these changes
Did some changes @dcroote can you take a look before I merge

2024-04-24 06:21 UTC, dcroote requested changes
Reads very well overall 👍 

Needs update:
https://github.com/api3dao/vitepress-docs/blob/35ad682bc139b72af31768448d781c37c1f6878b/docs/guides/dapis/read-a-dapi/index.md?plain=1#L94

I found a couple of pages under [Explore](https://docs.api3.org/explore/dapis/what-are-dapis.html) that need similar updating with regards to self/managed:

404:
https://github.com/api3dao/vitepress-docs/blob/35ad682bc139b72af31768448d781c37c1f6878b/docs/explore/dapis/what-are-dapis.md#L173

This whole page:

https://github.com/api3dao/vitepress-docs/blob/35ad682bc139b72af31768448d781c37c1f6878b/docs/explore/dapis/using-dapis.md#L25-L40

2024-04-24 06:21 UTC, dcroote commented on docs/guides/dapis/subscribing-to-dapis/index.md
> +purchase and activate it.
This sentence reads a bit out of order given the sentence above it starts with "If a dAPI is already activated..."

2024-04-24 06:21 UTC, dcroote commented on docs/reference/dapis/understand/index.md
> +[Datafeed values are stored on-chain](/reference/dapis/understand/#values-stored-on-chain)
This link is to its own section?

2024-04-24 06:21 UTC, dcroote commented on docs/reference/dapis/understand/index.md
> +[Airseeker](/reference/dapis/understand/dapis.md#airseeker) and other entities
404 for Airseeker link

2024-04-24 06:21 UTC, dcroote commented on docs/reference/dapis/understand/wallets.md
>  > **Data feed updates:**
404 on the `read()` link above

2024-04-24 06:23 UTC, dcroote commented on docs/guides/dapis/subscribing-to-dapis/index.md
> +amount of the subscription. If everything looks good, click on **Purchase**.
This reads as a near perfect duplicate of lines 51-56 above. I think it makes more sense here.

2024-04-25 06:18 UTC, dcroote commented on docs/guides/dapis/read-a-dapi/index.md
There is still an occurrence of `@api3/contracts/v0.8/interfaces` in lines 93-97

2024-04-27 13:48 UTC, vanshwassan commented
> One minor change still needed, otherwise LGTM.
> 
> I might suggest merging this when the explore PR is also ready, otherwise there will be broken links and discordant content.

 I have merged `Explore_2.1_March17` into this branch and closed https://github.com/api3dao/vitepress-docs/pull/726. Also updated the links.

2024-04-29 04:29 UTC, merged